"""Generate the atan approximation data; Python standard library only."""
import math
from pathlib import Path
from fit_atan_rational import fit

# Chebyshev interpolation of atan(sqrt(u))/sqrt(u), u in [0,1].
n = 10
samples = [(math.cos(math.pi*(k+.5)/n)+1)/2 for k in range(n)]
values = [math.atan(math.sqrt(u))/math.sqrt(u) for u in samples]
c = [2/n*sum(values[k]*math.cos(j*math.pi*(k+.5)/n) for k in range(n)) for j in range(n)]
c[0] *= .5
p0, p1 = [1.0], [-1.0, 2.0]
coeff = [c[0]] + [0.0]*(n-1)
for j in range(1,n):
    for k,v in enumerate(p1): coeff[k] += c[j]*v
    nxt = [0.0]*(len(p1)+1)
    for k,v in enumerate(p1): nxt[k] -= 2*v; nxt[k+1] += 4*v
    for k,v in enumerate(p0): nxt[k] -= v
    p0,p1 = p1,nxt
f = lambda v: f'{v:.10e}f'
out = ['// Generated by gen_atan.py; do not edit coefficients by hand.', '#pragma once',
       '#if B3_TWIST_APPROX == 2 || B3_TWIST_APPROX == 3',
       'static const float b3_atan_host[257] = {']
table = ',\n'.join('    '+', '.join(f(math.atan(i/256)) for i in range(j,min(j+4,257))) for j in range(0,257,4))
out += [table, '};', '#ifdef __CUDACC__', '#if B3_TWIST_APPROX == 3',
        'static __device__ __constant__ float b3_atan_device[257] = {', '#else',
        'static __device__ const float b3_atan_device[257] = {', '#endif', table, '};', '#endif', '#endif',
        'B3_HD B3_INL float b3_atan_unit(float r) {', '#if B3_TWIST_APPROX == 1',
        '    float u = r*r;', '    float p = '+f(coeff[-1])+';']
for v in reversed(coeff[:-1]): out += ['    p = fmaf(p, u, '+f(v)+');']
abc, _, _ = fit()
out += ['    return r*p;', '#elif B3_TWIST_APPROX == 4',
        '    float u = r*r;',
        '    return r * fmaf('+f(abc[1])+', u, '+f(abc[0])+') / fmaf('+f(abc[2])+', u, 1.0f);',
        '#else', '    float x = r*256.0f;',
        '    int i = (int)x;', '    i = i < 256 ? i : 255;',
        '#ifdef __CUDA_ARCH__', '    const float* table = b3_atan_device;', '#else',
        '    const float* table = b3_atan_host;', '#endif',
        '    return fmaf(x-i, table[i+1]-table[i], table[i]);', '#endif', '}']
Path(__file__).with_name('atan_approx.cuh').write_text('\n'.join(out)+'\n')
